log4j.rootLogger=info,console
log4j.logger.com.lonebytesoft.hamster.eventnotifybot=debug

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.EnhancedPatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%t] %-5p %c - %m%n
